name: Security

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vulns:
    name: Nancy scanner
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      -
        name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      -
        name: Run go list
        run: go list -json -m all > go.list
      -
        name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2

  trivy:
    name: Trivy scanner
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read

    steps:
      -
        name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v3
      -
        name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'